name: GitHub Profile Views Counter CI
on:
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:
jobs:
  release:
    name: GitHub Profile Views Counter Action
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.INSIGHTS_TOKEN }}
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.17.0
      - uses: gayanvoice/github-profile-views-counter-action@master
        env:
          INSIGHTS_TOKEN: ${{ secrets.INSIGHTS_TOKEN }}
